# Generated by Django 3.2.7 on 2022-06-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('itm_desc', models.CharField(max_length=200)),
                ('itm_price', models.IntegerField()),
            ],
        ),
    ]
