# Generated by Django 3.2.7 on 2022-06-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.dirtyapronrecipes.com/wp-content/uploads/2015/10/food-placeholder.png', max_length=500),
        ),
    ]
